function [binaryVector] = hexToBinaryVectorNL(hexDigit)
%This function takes in a hex digit and converts it to a binary vector.
%This was written becasue all liscences for the data aquision toolbox were
%being used and all we were using from that toolbox was this function.
%
%hexDigit - Is a char
%
%binaryVector - Is a vector;
%
% Ari Rubinsztejn
% a.rubin1225@gmail.com
% www.gereshes.com

dict={'0',[0,0,0,0];...
    '1',[0,0,0,1];...
    '2',[0,0,1,0];...
    '3',[0,0,1,1];...
    '4',[0,1,0,0];...
    '5',[0,1,0,1];...
    '6',[0,1,1,0];...
    '7',[0,1,1,1];...
    '8',[1,0,0,0];...
    '9',[1,0,0,1];...
    'A',[1,0,1,0];...
    'B',[1,0,1,1];...
    'C',[1,1,0,0];...
    'D',[1,1,0,1];...
    'E',[1,1,1,0];...
    'F',[1,1,1,1];};

binaryVector=dict{find(strcmpi(dict,hexDigit) == 1),2}; %#ok<FNDSB> 

end
